import json
from pathlib import Path
p = Path('C:/Users/Administrator/Desktop/AETHERION-WCS/configs/races.json')
obj = json.loads(p.read_text(encoding='utf-8'))
# Batch D6-D8 updates in ONE go with compact definitions
updates = {
  2125: {'name':'Тень Рока','abilities':[{'n':'Катаклизм Тени','t':'Passive','max':5,'d':'Увеличивает урон в темноте','effect':'conditional_buff','value':22},{'n':'Кинжал Тени','t':'Active','max':4,'d':'Телепорт за спину врага','effect':'blink','value':290,'cd':16},{'n':'Теневой Вихрь','t':'Ultimate','max':5,'d':'Вихрь клинков вокруг с отбрасыванием','effect':'frost_nova','value':34,'cd':36}]},
  2126: {'name':'Хранитель Рассвета','abilities':[{'n':'Рассветная Аура','t':'Passive','max':5,'d':'Хил союзников при свете','effect':'conditionalbuff','value':24},{'n':'Луч Света','t':'Active','max':4,'d':'Оглушает врагов лучом','effect':'stun_aoe','value':30,'cd':18},{'n':'Щит Рассвета','t':'Ultimate','max':5,'d':'Щит на всю команду','effect':'summon_ward','value':180,'cd':36}]},
  2127: {'name':'Повелитель Туманов','abilities':[{'n':'Туманное Покров','t':'Passive','max':5,'d':'Снижает урон в тумане','effect':'shield','value':32},{'n':'Рассеивание','t':'Active','max':4,'d':'Рассеивает вражеские туманы','effect':'slow','value':38,'cd':18},{'n':'Призыв Тумана','t':'Ultimate','max':5,'d':'Зона тумана с замедлением+уроном','effect':'frost_nova','value':34,'cd':36}]},
  2128: {'name':'Кровавая Дева','abilities':[{'n':'Кровавая Жажда','t':'Passive','max':5,'d':'Вампиризм при низком HP','effect':'lifesteal_passive','value':28},{'n':'Клинок Крови','t':'Active','max':4,'d':'Рывок с разлетом крови','effect':'nova_knockback','value':32,'cd':18},{'n':'Кровавая Буря','t':'Ultimate','max':5,'d':'Массовый вампиризм','effect':'lifesteal_passive','value':30,'cd':36}]},
  2129: {'name':'Заклинатель Льда','abilities':[{'n':'Ледяная Кровь','t':'Passive','max':5,'d':'Замедляет атакующих','effect':'slow','value':38},{'n':'Ледяная Игла','t':'Active','max':4,'d':'Снаряд с замораживанием','effect':'frost_nova','value':26,'cd':18},{'n':'Ледяная Тюрьма','t':'Ultimate','max':5,'d':'Замораживает врагов на месте','effect':'stun_aoe','value':32,'cd':36}]},
  2130: {'name':'Хранитель Огня','abilities':[{'n':'Огненное Пламя','t':'Passive','max':5,'d':'Поджигает атакующих','effect':'damage_reflect','value':30},{'n':'Огненный Шар','t':'Active','max':4,'d':'Снаряд с поджиганием','effect':'aoe_explosion','value':28,'cd':18},{'n':'Огненная Буря','t':'Ultimate','max':5,'d':'Дождь огня по зоне','effect':'slow','value':40,'cd':36}]},
  2131: {'name':'Маг Ветров','abilities':[{'n':'Ветер-Лезвие','t':'Passive','max':5,'d':'Ускоряет атаки при движении','effect':'cooldown_reduction','value':14},{'n':'Вихрь Ветра','t':'Active','max':4,'d':'Зона ветра с замедлением','effect':'slow','value':38,'cd':18},{'n':'Ураган','t':'Ultimate','max':5,'d':'Оглушает и сбивает','effect':'nova_knockback','value':36,'cd':36}]},
  2132: {'name':'Повелитель Земли','abilities':[{'n':'Каменная Кожа','t':'Passive','max':5,'d':'Снижает урон при низком HP','effect':'shield','value':34},{'n':'Каменная Стена','t':'Active','max':4,'d':'Создаёт преграду','effect':'summon_ward','value':150,'cd':18},{'n':'Землетрясение','t':'Ultimate','max':5,'d':'Сейсмический толчок','effect':'stun_aoe','value':32,'cd':36}]},
  2133: {'name':'Шквал Теней','abilities':[{'n':'Теневой Коготь','t':'Passive','max':5,'d':'Шанс пробить броню','effect':'armor_break','value':24},{'n':'Шквал Ножей','t':'Active','max':4,'d':'Серия ударов по прямой','effect':'crit_chance','value':28,'cd':16},{'n':'Теневая Буря','t':'Ultimate','max':5,'d':'Вихрь клинков вокруг','effect':'frost_nova','value':32,'cd':36}]},
  2134: {'name':'Варлок Бездны','abilities':[{'n':'Кровь Бездны','t':'Passive','max':5,'d':'Вампиризм от магического урона','effect':'lifesteal_passive','value':26},{'n':'Тень Бездны','t':'Active','max':4,'d':'Скачок с разрядом тьмы','effect':'berserk','value':24,'cd':18},{'n':'Проклятие Бездны','t':'Ultimate','max':5,'d':'Проклинает врагов','effect':'chain_lightning','value':135,'cd':36}]},
  2135: {'name':'Стальной Лис','abilities':[{'n':'Стальной Хвост','t':'Passive','max':5,'d':'Отражает урон при ударе','effect':'damage_reflect','value':28},{'n':'Лисья Хитрость','t':'Active','max':4,'d':'Слепой телепорт в тыл','effect':'blink','value':280,'cd':16},{'n':'Стальной Шквал','t':'Ultimate','max':5,'d':'Круговой удар поочередными ударами','effect':'frost_nova','value':32,'cd':36}]},
  2136: {'name':'Молния-Катализатор','abilities':[{'n':'Кладовая Энергии','t':'Passive','max':5,'d':'Накопление урона молнией','effect':'chain_lightning','value':20},{'n':'Перегрузка','t':'Active','max':4,'d':'Выстрел молнией с разрядом','effect':'aoe_explosion','value':30,'cd':18},{'n':'Цепной Разряд','t':'Ultimate','max':5,'d':'Цепная молния по 4 целям','effect':'chain_lightning','value':145,'cd':36}]},
  2137: {'name':'Страж Рассвета','abilities':[{'n':'Рассветный Щит','t':'Passive','max':5,'d':'Снижает урон при свете','effect':'shield','value':32},{'n':'Рассветный Удар','t':'Active','max':4,'d':'Рывок с ослеплением','effect':'stun_aoe','value':30,'cd':18},{'n':'Сияние Рассвета','t':'Ultimate','max':5,'d':'Ослепляет и хилит союзников','effect':'summon_ward','value':170,'cd':36}]},
  2138: {'name':'Кинетик Времени','abilities':[{'n':'Хронопокров','t':'Passive','max':5,'d':'Снижает КД за время','effect':'cooldown_reduction','value':14},{'n':'Рваная Время','t':'Active','max':4,'d':'Телепорт с задержкой времени','effect':'blink','value':300,'cd':18},{'n':'Стоп-Время','t':'Ultimate','max':5,'d':'Останавливает врагов','effect':'nova_knockback','value':36,'cd':38}]},
  2139: {'name':'Зов Звёзд','abilities':[{'n':'Звёздная Аура','t':'Passive','max':5,'d':'Увеличивает критический удар','effect':'crit_chance','value':30},{'n':'Метеоритный Дождь','t':'Active','max':4,'d':'Дождь метеоритов по зоне','effect':'aoe_explosion','value':32,'cd':18},{'n':'Звёздный Шторм','t':'Ultimate','max':5,'d':'Шквал звёзд с замедлением','effect':'frost_nova','value':34,'cd':36}]},
  2140: {'name':'Живая Бездна','abilities':[{'n':'Бездонный Покров','t':'Passive','max':5,'d':'Поглощает урон в щит','effect':'mana_shield','value':28},{'n':'Разлом Пустоты','t':'Active','max':4,'d':'Тянет врагов к центру','effect':'slow','value':38,'cd':18},{'n':'Концентрация Бездны','t':'Ultimate','max':5,'d':'Массовый урон+отбрасывание','effect':'nova_knockback','value':36,'cd':36}]},
  2141: {'name':'Драконья Кровь','abilities':[{'n':'Драконья Чешуя','t':'Passive','max':5,'d':'Снижает урон при низком HP','effect':'shield','value':32},{'n':'Дыхание Дракона','t':'Active','max':4,'d':'Огненный луч по прямой','effect':'armor_break','value':32,'cd':18},{'n':'Крыло Дракона','t':'Ultimate','max':5,'d':'Взмах крыльев с отбрасыванием','effect':'nova_knockback','value':38,'cd':36}]},
  2142: {'name':'Клинок Тысячи Лезвий','abilities':[{'n':'Режущий Поток','t':'Passive','max':5,'d':'Шанс разрезать врага','effect':'crit_chance','value':30},{'n':'Секущий Вихрь','t':'Active','max':4,'d':'Серия ударов по области','effect':'frost_nova','value':30,'cd':16},{'n':'Таран Лезвия','t':'Ultimate','max':5,'d':'Рывок через врагов с критом','effect':'berserk','value':30,'cd':36}]},
  2143: {'name':'Хранитель Заветов','abilities':[{'n':'Заветная Аура','t':'Passive','max':5,'d':'Усиливает союзников рядом','effect':'conditionalbuff','value':24},{'n':'Щит Заветов','t':'Active','max':4,'d':'Накладывает щит на цель','effect':'summon_ward','value':150,'cd':20},{'n':'Кара Заветов','t':'Ultimate','max':5,'d':'Оглушает+урон по зоне','effect':'stun_aoe','value':34,'cd':36}]},
  2144: {'name':'Молот Титана','abilities':[{'n':'Титановы Мышцы','t':'Passive','max':5,'d':'Увеличивает урон при низком HP','effect':'Execute_low_hp','value':32},{'n':'Титанов Удар','t':'Active','max':4,'d':'Удар по земле с сотрясением','effect':'nova_knockback','value':32,'cd':18},{'n':'Гнев Титана','t':'Ultimate','max':5,'d':'Мощный удар по зоне','effect':'stun_aoe','value':34,'cd':36}]},
  2145: {'name':'Вестник Тьмы','abilities':[{'n':'Покров Тьмы','t':'Passive','max':5,'d':'Снижает защиту врагов рядом','effect':'magic_damage_amp','value':24},{'n':'Теневой Рывок','t':'Active','max':4,'d':'Рывок с уроном по дуге','effect':'blink','value':300,'cd':18},{'n':'Крик Тьмы','t':'Ultimate','max':5,'d':'Оглушает и наносит урон','effect':'frost_nova','value':34,'cd':36}]},
  2146: {'name':'Солнечный Зов','abilities':[{'n':'Солнечная Аура','t':'Passive','max':5,'d':'Хил союзников рядом','effect':'conditionalbuff','value':24},{'n':'Солнечный Луч','t':'Active','max':4,'d':'Луч по прямой с уроном','effect':'armor_break','value':30,'cd':18},{'n':'Солнечная Буря','t':'Ultimate','max':5,'d':'Массовый урон+хил','effect':'summon_ward','value':180,'cd':36}]},
  2147: {'name':'Хаотичный Бунтарь','abilities':[{'n':'Хаос-Бафф','t':'Passive','max':5,'d':'Случайный бафф/дебафф на врагов','effect':'conditional_buff','value':22},{'n':'Скачок Хаоса','t':'Active','max':4,'d':'Случайный телепорт вокруг врага','effect':'blink','value':280,'cd':16},{'n':'Катаклизм Хаоса','t':'Ultimate','max':5,'d':'Беспорядочные удары','effect':'nova_knockback','value':36,'cd':36}]},
  2148: {'name':'Шипастый Страж','abilities':[{'n':'Шипы','t':'Passive','max':5,'d':'Наносит урон при ударе','effect':'damage_reflect','value':28},{'n':'Шипастая Стена','t':'Active','max':4,'d':'Создаёт преграду с шипами','effect':'summon_ward','value':150,'cd':18},{'n':'Шипастый Вихрь','t':'Ultimate','max':5,'d':'Вращение шипов вокруг','effect':'frost_nova','value':32,'cd':36}]},
  2149: {'name':'Свет Правды','abilities':[{'n':'Аура Правды','t':'Passive','max':5,'d':'Увеличивает урон по иллюзиям','effect':'magic_damage_amp','value':24},{'n':'Луч Правды','t':'Active','max':4,'d':'Выстрел с обезоруживанием','effect':'slow','value':38,'cd':18},{'n':'Свет Правды','t':'Ultimate','max':5,'d':'Ослепляет и наносит урон','effect':'stun_aoe','value':32,'cd':36}]},
  2150: {'name':'Маг Водопада','abilities':[{'n':'Водный Поток','t':'Passive','max':5,'d':'Шанс увернуться у воды','effect':'evasion_chance','value':22},{'n':'Водопад','t':'Active','max':4,'d':'Ударная волна водой','effect':'berserk','value':24,'cd':18},{'n':'Водяная Буря','t':'Ultimate','max':5,'d':'Стена воды с замедлением+уроном','effect':'slow','value':40,'cd':36}]},
}
idx_by_id = {r['id']: i for i, r in enumerate(obj)}
for rid,info in updates.items():
    idx = idx_by_id[rid]
    obj[idx]['name'] = info['name']
    obj[idx]['abilities'] = info['abilities']
p.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding='utf-8')
print('batch_D7_part applied', len(updates))
