import json
from pathlib import Path
p = Path('C:/Users/Administrator/Desktop/AETHERION-WCS/configs/races.json')
obj = json.loads(p.read_text(encoding='utf-8'))
idx_by_id = {r['id']: i for i, r in enumerate(obj)}
updates = {
  # D7
  2175: {'name':'Слаггер Грома','abilities':[{'n':'Громовой Удар','t':'Passive','max':5,'d':'Шанс оглушить','effect':'stun_aoe','value':28},{'n':'Подавитель','t':'Active','max':4,'d':'Подавляет враговAoE','effect':'nova_knockback','value':30,'cd':18},{'n':'Громовой Зов','t':'Ultimate','max':5,'d':'Ударная волна поAoE','effect':'aoe_explosion','value':34,'cd':36}]},
  2176: {'name':'Ночной Сталкер','abilities':[{'n':'Полная Невидимость','t':'Passive','max':5,'d':'Невидимость при бездействии','effect':'invisibility','value':38},{'n':'Ассасин Удар','t':'Active','max':4,'d':'Удар сзади','effect':'blink','value':300,'cd':16},{'n':'Ночь Ужаса','t':'Ultimate','max':5,'d':'СтрахAoE','effect':'stun_aoe','value':32,'cd':36}]},
  2177: {'name':'Никс Пружинчик','abilities':[{'n':'Генератор','t':'Passive','max':5,'d':'Случайный бонус урона','effect':'conditional_buff','value':22},{'n':'Скачок Пружины','t':'Active','max':4,'d':'Рывок с ускорением','effect':'berserk','value':24,'cd':16},{'n':'Безумие Механизма','t':'Ultimate','max':5,'d':'Разлетающиеся ударыAoE','effect':'frost_nova','value':32,'cd':36}]},
  2178: {'name':'Алгалон Наблюдатель','abilities':[{'n':'Звёздная Аура','t':'Passive','max':5,'d':'Снижает магический урон','effect':'shield','value':32},{'n':'Звёздная Стрела','t':'Active','max':4,'d':'ЛучAoE по прямой','effect':'aoe_explosion','value':30,'cd':18},{'n':'Свершение Приговора','t':'Ultimate','max':5,'d':'Снижает урон враговAoE','effect':'magic_damage_amp','value':24,'cd':36}]},
  2179: {'name':'Тинкмастер','abilities':[{'n':'Изобретатель','t':'Passive','max':5,'d':'Взрывы вокруг','effect':'aoe_explosion','value':22},{'n':'Минное Поле','t':'Active','max':4,'d':'Минное поле','effect':'slow','value':38,'cd':18},{'n':'Супербомба','t':'Ultimate','max':5,'d':'МощныйAoE взрыв','effect':'stun_aoe','value':34,'cd':36}]},
  2180: {'name':'Харлут Искра','abilities':[{'n':'Искра Энергии','t':'Passive','max':5,'d':'Накопление урона молнией','effect':'chain_lightning','value':20},{'n':'Чардж','t':'Active','max':4,'d':'Рывок с волной','effect':'leap','value':300,'cd':16},{'n':'Энергетический Взрыв','t':'Ultimate','max':5,'d':'Цепной взрыв','effect':'chain_lightning','value':145,'cd':36}]},
  2181: {'name':'Пожиратель','abilities':[{'n':'Поглощение','t':'Passive','max':5,'d':'Вампиризм от урона','effect':'lifesteal_passive','value':26},{'n':'Бездна','t':'Active','max':4,'d':'Скачок сAoE уроном','effect':'berserk','value':24,'cd':18},{'n':'Пожирание Душ','t':'Ultimate','max':5,'d':'Массовый вампиризм','effect':'lifesteal_passive','value':28,'cd':36}]},
  2182: {'name':'Ронин Титан','abilities':[{'n':'Клинок Почёта','t':'Passive','max':5,'d':'Шанс пробить броню','effect':'armor_break','value':28},{'n':'Секущий Рывок','t':'Active','max':4,'d':'Серия ударов по дуге','effect':'frost_nova','value':28,'cd':16},{'n':'Движение Титана','t':'Ultimate','max':5,'d':'ОтбрасываетAoE','effect':'nova_knockback','value':36,'cd':36}]},
  2183: {'name':'Краб-Воин','abilities':[{'n':'Клешня','t':'Passive','max':5,'d':'Сила наносит больше урона','effect':'Execute_low_hp','value':32},{'n':'Укус','t':'Active','max':4,'d':'Ядовитый укус','effect':'slow','value':38,'cd':18},{'n':'Краб-Шторм','t':'Ultimate','max':5,'d':'ЗахватываетAoE','effect':'stun_aoe','value':32,'cd':36}]},
  2184: {'name':'Фобия','abilities':[{'n':'Страх','t':'Passive','max':5,'d':'Снижает защиту врагов','effect':'magic_damage_amp','value':24},{'n':'Проклятие','t':'Active','max':4,'d':'Проклинает цель','effect':'slow','value':38,'cd':18},{'n':'Паника','t':'Ultimate','max':5,'d':'РазбегаютсяAoE','effect':'nova_knockback','value':30,'cd':36}]},
  2185: {'name':'Древний Лорд Огня','abilities':[{'n':'Пламя Души','t':'Passive','max':5,'d':'Хил при поджигании','effect':'lifesteal_passive','value':24},{'n':'Шар Огня','t':'Active','max':4,'d':'Снаряд с поджиганием','effect':'aoe_explosion','value':28,'cd':18},{'n':'Дыхание Дракона','t':'Ultimate','max':5,'d':'ДлинныйAoE луч','effect':'fire_breath','value':320,'cd':36}]},
  2186: {'name':'Век'Налаш','abilities':[{'n':'Пламя Бездны','t':'Passive','max':5,'d':'Поджигает врагов','effect':'damage_reflect','value':30},{'n':'Кинжал Тирада','t':'Active','max':4,'d':'Рывок с ударом в спину','effect':'blink','value':290,'cd':16},{'n':'Ярость Бездны','t':'Ultimate','max':5,'d':'ВихрьAoE','effect':'frost_nova','value':34,'cd':36}]},
  2187: {'name':'Деус Машина','abilities':[{'n':'Перегрузка','t':'Passive','max':5,'d':'Накопление урона','effect':'chain_lightning','value':22},{'n':'Плазма-Заряд','t':'Active','max':4,'d':'Выстрел плазмойAoE','effect':'armor_break','value':30,'cd':18},{'n':'Цепной Перегруз','t':'Ultimate','max':5,'d':'Цепной разряд','effect':'chain_lightning','value':140,'cd':36}]},
  2188: {'name':'Смертокрыл','abilities':[{'n':'Чешуя Смерти','t':'Passive','max':5,'d':'Снижает урон при низком HP','effect':'shield','value':32},{'n':'Крыло Смерти','t':'Active','max':4,'d':'Взмах крыльями с отбрасыванием','effect':'nova_knockback','value':38,'cd':18},{'n':'Дыхание Мира','t':'Ultimate','max':5,'d':'Огненный лучAoE','effect':'fire_breath','value':360,'cd':36}]},
  2189: {'name':'Таймшифтер','abilities':[{'n':'Пространственный Сдвиг','t':'Passive','max':5,'d':'Снижает КД','effect':'cooldown_reduction','value':14},{'n':'Рваная Сингулярность','t':'Active','max':4,'d':'Скачок с замедлением','effect':'slow','value':38,'cd':18},{'n':'Переписка','t':'Ultimate','max':5,'d':'Возвращает враговAoE','effect':'blink','value':300,'cd':36}]},
  2190: {'name':'Король Лич','abilities':[{'n':'Нежить','t':'Passive','max':5,'d':'Вампиризм от урона','effect':'lifesteal_passive','value':26},{'n':'Ледяная Плоть','t':'Active','max':4,'d':'ЗамораживаетAoE','effect':'frost_nova','value':30,'cd':18},{'n':'Фрез Ледяной','t':'Ultimate','max':5,'d':'Замораживает на месте','effect':'stun_aoe','value':32,'cd':36}]},
  2191: {'name':'Отступник Охотник','abilities':[{'n':'Скрытность','t':'Passive','max':5,'d':'Невидимый при неподвижности','effect':'invisibility','value':34},{'n':'Снайперский Выстрел','t':'Active','max':4,'d':'Дальний выстрел с уроном','effect':'armor_break','value':32,'cd':18},{'n':'Натиск Отступника','t':'Ultimate','max':5,'d':'Двойной выстрел','effect':'crit_chance','value':34,'cd':36}]},
  2192: {'name':'Серафим','abilities':[{'n':'Аура Света','t':'Passive','max':5,'d':'Хил союзников рядом','effect':'conditionalbuff','value':24},{'n':'Жезл Света','t':'Active','max':4,'d':'ОглушаетAoE','effect':'stun_aoe','value':30,'cd':18},{'n':'Щит Серафима','t':'Ultimate','max':5,'d':'Щит на команду','effect':'summon_ward','value':180,'cd':36}]},
  2193: {'name':'Киллер Физик','abilities':[{'n':'Расчёт','t':'Passive','max':5,'d':'Увеличение урона при низком HP','effect':'Execute_low_hp','value':30},{'n':'Микроудар','t':'Active','max':4,'d':'Мгновенный удар','effect':'blink','value':290,'cd':16},{'n':'Квантовый Разлом','t':'Ultimate','max':5,'d':'Урон+отбрасываниеAoE','effect':'nova_knockback','value':34,'cd':36}]},
  2194: {'name':'Скрытный Друид','abilities':[{'n':'Связь с Природой','t':'Passive','max':5,'d':'Хил на траве','effect':'conditionalbuff','value':22},{'n':'Зов Звериный','t':'Active','max':4,'d':'Призывает зверя assistance','effect':'pet_swarm','value':6,'cd':18},{'n':'Дубовая Кожа','t':'Ultimate','max':5,'d':'Щит на команду','effect':'summon_ward','value':180,'cd':36}]},
  2195: {'name':'Воин Легиона','abilities':[{'n':'Боевой Порядок','t':'Passive','max':5,'d':'Усиливает союзников рядом','effect':'conditionalbuff','value':24},{'n':'Штурм','t':'Active','max':4,'d':'Рывок сAoE уроном','effect':'leap','value':300,'cd':18},{'n':'Тактический Удар','t':'Ultimate','max':5,'d':'Оглушает+уронAoE','effect':'stun_aoe','value':34,'cd':36}]},
  2196: {'name':'Древний Лорд Воздуха','abilities':[{'n':'Удушье','t':'Passive','max':5,'d':'Замедляет врагов рядом','effect':'slow','value':38},{'n':'Ураган','t':'Active','max':4,'d':'Отбрасывает и оглушаетAoE','effect':'nova_knockback','value':36,'cd':18},{'n':'Глаз Бури','t':'Ultimate','max':5,'d':'Цепная молния','effect':'chain_lightning','value':140,'cd':36}]},
  2197: {'name':'Скрытный Разбойник','abilities':[{'n':'Скрытность','t':'Passive','max':5,'d':'Невидимый при атаке из-под cover','effect':'invisibility','value':36},{'n':'Удар в Спину','t':'Active','max':4,'d':'Мгновенный удар с критом','effect':'blink','value':290,'cd':16},{'n':'Танец Клинков','t':'Ultimate','max':5,'d':'Вихрь клинков вокруг','effect':'frost_nova','value':32,'cd':36}]},
}
idx_by_id = {r['id']: i for i, r in enumerate(obj)}
for rid,info in updates.items():
    idx=idx_by_id[rid]; obj[idx]['name']=info['name']; obj[idx]['abilities']=info['abilities']
p.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding='utf-8')
print('D7_D8 batch:', len(updates))
