import json, pathlib

p = pathlib.Path('C:/Users/Administrator/Desktop/AETHERION-WCS/configs/races.json')
obj = json.loads(p.read_text(encoding='utf-8'))
idx_by_id = {r['id']: i for i, r in enumerate(obj)}

updates = {
    2100: { 'name': 'Война Пепла', 'abilities': [ {'n': 'Пепел Памяти', 't': 'Passive', 'max': 5, 'd': 'Хил при взрывах рядом · Пассивно · макс 5', 'effect': 'conditionalbuff', 'value': 22}, {'n': 'Послевзрыв', 't': 'Active', 'max': 4, 'd': 'Телепорт после удара с доп. уроном · Актив · макс 4 · КД 18с', 'effect': 'blink', 'value': 280, 'cd': 18}, {'n': 'Кольцо Пепла', 't': 'Ultimate', 'max': 5, 'd': 'ПостоянныйAoE огонь по кругу · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 34, 'cd': 36} ] },
    2101: { 'name': 'Хранитель Врат', 'abilities': [ {'n': 'Аура Защиты', 't': 'Passive', 'max': 5, 'd': 'Снижает урон союзников рядом · Пассивно · макс 5', 'effect': 'shield', 'value': 28}, {'n': 'Врата Щита', 't': 'Active', 'max': 4, 'd': 'Создаёт непроходимый барьер · Актив · макс 4 · КД 20с', 'effect': 'summon_ward', 'value': 160, 'cd': 20}, {'n': 'Замок Погибели', 't': 'Ultimate', 'max': 5, 'd': 'Оглушает и отталкиваетAoE · Ульта · макс 5 · КД 36с', 'effect': 'nova_knockback', 'value': 35, 'cd': 36} ] },
    2102: { 'name': 'Кинетик Разума', 'abilities': [ {'n': 'Пси-Щит', 't': 'Passive', 'max': 5, 'd': 'Щит при получении урона · Пассивно · макс 5', 'effect': 'mana_shield', 'value': 28}, {'n': 'Подавление', 't': 'Active', 'max': 4, 'd': 'Оглушает цель и замедляет · Актив · макс 4 · КД 18с', 'effect': 'slow', 'value': 38, 'cd': 18}, {'n': 'Psionic Взрыв', 't': 'Ultimate', 'max': 5, 'd': 'Цепной взрыв по разуму · Ульта · макс 5 · КД 36с', 'effect': 'chain_lightning', 'value': 140, 'cd': 36} ] },
    2103: { 'name': 'Жнец Кошмара', 'abilities': [ {'n': 'Тень Жнеца', 't': 'Passive', 'max': 5, 'd': 'Шанс скрыть подход · Пассивно · макс 5', 'effect': 'invisibility', 'value': 36}, {'n': 'Коса Души', 't': 'Active', 'max': 4, 'd': 'Мгновенный удар по дуге · Актив · макс 4 · КД 16с', 'effect': 'blink', 'value': 290, 'cd': 16}, {'n': 'Коса Смерти', 't': 'Ultimate', 'max': 5, 'd': 'Massive уронAoE + испепеление · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 34, 'cd': 36} ] },
    2104: { 'name': 'Титан-Вулкан', 'abilities': [ {'n': 'Огненная Кожa', 't': 'Passive', 'max': 5, 'd': 'Поджигает атакующих близко · Пассивно · макс 5', 'effect': 'damage_reflect', 'value': 30}, {'n': 'Извержение', 't': 'Active', 'max': 4, 'd': 'Скачок с извержением лавыAoE · Актив · макс 4 · КД 18с', 'effect': 'aoe_explosion', 'value': 30, 'cd': 18}, {'n': 'Магмовое Пламя', 't': 'Ultimate', 'max': 5, 'd': 'Поле лавы: замедляет+урон · Ульта · макс 5 · КД 36с', 'effect': 'slow', 'value': 40, 'cd': 36} ] },
    2105: { 'name': 'Картограф Войны', 'abilities': [ {'n': 'Секторный Анализ', 't': 'Passive', 'max': 5, 'd': 'Ускоряет перезарядка + снижает уклонение · Пассивно · макс 5', 'effect': 'cooldown_reduction', 'value': 14}, {'n': 'Маркер Цели', 't': 'Active', 'max': 4, 'd': 'Помечает врага для команды · Актив · макс 4 · КД 18с', 'effect': 'slow', 'value': 36, 'cd': 18}, {'n': 'Артиллерийский Залп', 't': 'Ultimate', 'max': 5, 'd': 'Подавляющий огонь поAoE · Ульта · макс 5 · КД 36с', 'effect': 'aoe_explosion', 'value': 34, 'cd': 36} ] },
    2106: { 'name': 'Скоростной Шершень', 'abilities': [ {'n': 'Штурмовик', 't': 'Passive', 'max': 5, 'd': 'Увеличивает скорость после убийства · Пассивно · макс 5', 'effect': 'berserk', 'value': 28}, {'n': 'Ударная Волна', 't': 'Active', 'max': 4, 'd': 'Скачок с отталкиваниемAoE · Актив · макс 4 · КД 16с', 'effect': 'nova_knockback', 'value': 30, 'cd': 16}, {'n': 'Десантный Удар', 't': 'Ultimate', 'max': 5, 'd': 'Садится в тыл врагаAoE · Ульта · макс 5 · КД 36с', 'effect': 'leap', 'value': 340, 'cd': 36} ] },
    2107: { 'name': 'Волчий Стастрел', 'abilities': [ {'n': 'Стальной Коготь', 't': 'Passive', 'max': 5, 'd': 'Шанс на критический удар · Пассивно · макс 5', 'effect': 'crit_chance', 'value': 28}, {'n': 'Волчья Связь', 't': 'Active', 'max': 4, 'd': 'Рывок с усилением атаки · Актив · макс 4 · КД 16с', 'effect': 'berserk', 'value': 24, 'cd': 16}, {'n': 'Стая Криков', 't': 'Ultimate', 'max': 5, 'd': 'Призывает волков на assistance · Ульта · макс 5 · КД 36с', 'effect': 'pet_swarm', 'value': 6, 'cd': 36} ] },
    2108: { 'name': 'Повелитель Грёз', 'abilities': [ {'n': 'Ночной Кошмар', 't': 'Passive', 'max': 5, 'd': 'Снижает защиту врагов ночью · Пассивно · макс 5', 'effect': 'magic_damage_amp', 'value': 22}, {'n': 'Сонная Аура', 't': 'Active', 'max': 4, 'd': 'Замедляет врагов вAoE · Актив · макс 4 · КД 18с', 'effect': 'slow', 'value': 38, 'cd': 18}, {'n': 'Кошмарное Пробуждение', 't': 'Ultimate', 'max': 5, 'd': 'СтрахAoE + урон по awoke · Ульта · макс 5 · КД 36с', 'effect': 'stun_aoe', 'value': 30, 'cd': 36} ] },
    2109: { 'name': 'Маг Стихий', 'abilities': [ {'n': 'Стихийный Баланс', 't': 'Passive', 'max': 5, 'd': 'Усиливает стихию противника · Пассивно · макс 5', 'effect': 'conditional_buff', 'value': 24}, {'n': 'Огненный Шар', 't': 'Active', 'max': 4, 'd': 'Снаряд AoE с поджиганием · Актив · макс 4 · КД 18с', 'effect': 'aoe_explosion', 'value': 28, 'cd': 18}, {'n': 'Землетрясение', 't': 'Ultimate', 'max': 5, 'd': 'Сейсмический толчокAoE · Ульта · макс 5 · КД 36с', 'effect': 'stun_aoe', 'value': 34, 'cd': 36} ] },
    2110: { 'name': 'Хранитель Копий', 'abilities': [ {'n': 'Аура Защиты', 't': 'Passive', 'max': 5, 'd': 'Снижает урон союзников рядом · Пассивно · макс 5', 'effect': 'shield', 'value': 30}, {'n': 'Копьё Правды', 't': 'Active', 'max': 4, 'd': 'Рывок с пробитием брони · Актив · макс 4 · КД 18с', 'effect': 'armor_break', 'value': 32, 'cd': 18}, {'n': 'Вихрь Копий', 't': 'Ultimate', 'max': 5, 'd': 'Спинальная атакаAoE по кругу · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 32, 'cd': 36} ] },
    2111: { 'name': 'Планетарный Страж', 'abilities': [ {'n': 'Гравитация', 't': 'Passive', 'max': 5, 'd': 'Замедляет врагов рядом · Пассивно · макс 5', 'effect': 'slow', 'value': 36}, {'n': 'Скачок Планеты', 't': 'Active', 'max': 4, 'd': 'Скачок с разлетом осколков · Актив · макс 4 · КД 18с', 'effect': 'leap', 'value': 320, 'cd': 18}, {'n': 'Кольцо Гравитации', 't': 'Ultimate', 'max': 5, 'd': 'Притягивает+оглушает врагов · Ульта · макс 5 · КД 36с', 'effect': 'nova_knockback', 'value': 38, 'cd': 36} ] },
    2112: { 'name': 'Ночной Дозор', 'abilities': [ {'n': 'Тёмный Дозор', 't': 'Passive', 'max': 5, 'd': 'Видит невидимых врагов · Пассивно · макс 5', 'effect': 'magic_damage_amp', 'value': 24}, {'n': 'Стрела Молчания', 't': 'Active', 'max': 4, 'd': 'Выстрел с обеззвучиванием · Актив · макс 4 · КД 18с', 'effect': 'slow', 'value': 38, 'cd': 18}, {'n': 'Прицел Тьмы', 't': 'Ultimate', 'max': 5, 'd': 'Гарантированный крит + урон по зоне · Ульта · макс 5 · КД 36с', 'effect': 'crit_chance', 'value': 34, 'cd': 36} ] },
    2113: { 'name': 'Алхимик Хаоса', 'abilities': [ {'n': 'Зелье Непредсказуемости', 't': 'Passive', 'max': 5, 'd': 'Случайный эффект на врагов · Пассивно · макс 5', 'effect': 'conditional_buff', 'value': 24}, {'n': 'Кристалл Взрыва', 't': 'Active', 'max': 4, 'd': 'Бросает кристаллAoE · Актив · макс 4 · КД 18с', 'effect': 'aoe_explosion', 'value': 28, 'cd': 18}, {'n': 'Эликсир Чумы', 't': 'Ultimate', 'max': 5, 'd': 'Зона болезни: урон+замедление · Ульта · макс 5 · КД 36с', 'effect': 'slow', 'value': 40, 'cd': 36} ] },
    2114: { 'name': 'Король-Шахтёр', 'abilities': [ {'n': 'Шахтёрский Щит', 't': 'Passive', 'max': 5, 'd': 'Снижает урон рудой · Пассивно · макс 5', 'effect': 'shield', 'value': 32}, {'n': 'Шахтный Взрыв', 't': 'Active', 'max': 4, 'd': 'Взрыв вAoE с отбрасыванием · Актив · макс 4 · КД 18с', 'effect': 'nova_knockback', 'value': 34, 'cd': 18}, {'n': 'Гигантская Дробилка', 't': 'Ultimate', 'max': 5, 'd': 'Удар по земле AoE · Ульта · макс 5 · КД 36с', 'effect': 'stun_aoe', 'value': 32, 'cd': 36} ] },
    2115: { 'name': 'Пламя Судьбы', 'abilities': [ {'n': 'Пламя Жизни', 't': 'Passive', 'max': 5, 'd': 'Восстанавливает HP при вреде врагам · Пассивно · макс 5', 'effect': 'lifesteal_passive', 'value': 24}, {'n': 'Огненный Шар', 't': 'Active', 'max': 4, 'd': 'Снаряд с поджиганием · Актив · макс 4 · КД 18с', 'effect': 'armor_break', 'value': 30, 'cd': 18}, {'n': 'Судебное Пламя', 't': 'Ultimate', 'max': 5, 'd': 'Дождь огня по зонеAoE · Ульта · макс 5 · КД 36с', 'effect': 'aoe_explosion', 'value': 32, 'cd': 36} ] },
}

# apply updates for IDs 2075-2115 (D4 and D5 first half)
for rid, info in updates.items():
    idx = idx_by_id[rid]
    obj[idx]['name'] = info['name']
    obj[idx]['abilities'] = info['abilities']

p.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding='utf-8')
print('D4+D5_part1 updated', len(updates))
