import json, pathlib

p = pathlib.Path('C:/Users/Administrator/Desktop/AETHERION-WCS/configs/races.json')
obj = json.loads(p.read_text(encoding='utf-8'))
idx_by_id = {r['id']: i for i, r in enumerate(obj)}

updates = {
    2075: { 'name': 'Закал Хранитель', 'abilities': [ {'n': 'Каменная Кожа', 't': 'Passive', 'max': 5, 'd': 'Снижает урон при низком HP · Пассивно · макс 5', 'effect': 'shield', 'value': 34}, {'n': 'Катаклизм', 't': 'Active', 'max': 4, 'd': 'Удар поAoE с отбрасыванием · Актив · макс 4 · КД 18с', 'effect': 'nova_knockback', 'value': 32, 'cd': 18}, {'n': 'Ледяная Темница', 't': 'Ultimate', 'max': 5, 'd': 'Замораживает врагов на месте · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 34, 'cd': 36} ] },
    2076: { 'name': 'Повелитель Стали', 'abilities': [ {'n': 'Генератор Амуниции', 't': 'Passive', 'max': 5, 'd': 'Ускоряет перезарядка оружия · Пассивно · макс 5', 'effect': 'cooldown_reduction', 'value': 14}, {'n': 'Плазменный Заряд', 't': 'Active', 'max': 4, 'd': 'Рывок с поджиганием цели · Актив · макс 4 · КД 16с', 'effect': 'armor_break', 'value': 32, 'cd': 16}, {'n': 'Артиллерия', 't': 'Ultimate', 'max': 5, 'd': 'Залп по зоне с замедлением · Ульта · макс 5 · КД 36с', 'effect': 'aoe_explosion', 'value': 34, 'cd': 36} ] },
    2077: { 'name': 'Призрак Виверны', 'abilities': [ {'n': 'Небесный Скрыт', 't': 'Passive', 'max': 5, 'd': 'Повышает критический урон при невидимости · Пассивно · макс 5', 'effect': 'invisibility', 'value': 38}, {'n': 'Ледяной Удар', 't': 'Active', 'max': 4, 'd': 'Серия ударов с замораживанием · Актив · макс 4 · КД 18с', 'effect': 'frost_nova', 'value': 26, 'cd': 18}, {'n': 'Феникс Взлёт', 't': 'Ultimate', 'max': 5, 'd': 'Поджигает враговAoE и усиливает себя · Ульта · макс 5 · КД 36с', 'effect': 'berserk', 'value': 30, 'cd': 36} ] },
    2078: { 'name': 'Рощик-Поколений', 'abilities': [ {'n': 'Живая Кора', 't': 'Passive', 'max': 5, 'd': 'Хил при нахождении на траве · Пассивно · макс 5', 'effect': 'conditionalbuff', 'value': 22}, {'n': 'Корневой Рывок', 't': 'Active', 'max': 4, 'd': 'Скачок с подбрасыванием врагов · Актив · макс 4 · КД 18с', 'effect': 'berserk', 'value': 24, 'cd': 18}, {'n': 'Ядовитый Плод', 't': 'Ultimate', 'max': 5, 'd': 'Зона токсина с замедлением · Ульта · макс 5 · КД 36с', 'effect': 'slow', 'value': 40, 'cd': 36} ] },
    2079: { 'name': 'Крик Титана', 'abilities': [ {'n': 'Железная Воля', 't': 'Passive', 'max': 5, 'd': 'Поглощает часть урона в щит · Пассивно · макс 5', 'effect': 'shield', 'value': 32}, {'n': 'Кулак Тора', 't': 'Active', 'max': 4, 'd': 'Удар по земле с сотрясением · Актив · макс 4 · КД 18с', 'effect': 'stun_aoe', 'value': 32, 'cd': 18}, {'n': 'Феникс-Крик', 't': 'Ultimate', 'max': 5, 'd': 'Взлет сAOE оглушение + отбрасывание · Ульта · макс 5 · КД 36с', 'effect': 'nova_knockback', 'value': 38, 'cd': 36} ] },
    2080: { 'name': 'Мутатор Энтропии', 'abilities': [ {'n': 'Хаотичный Сдвиг', 't': 'Passive', 'max': 5, 'd': 'Случайные бафф/дебафф на врагов · Пассивно · макс 5', 'effect': 'conditional_buff', 'value': 22}, {'n': 'Формула Разлома', 't': 'Active', 'max': 4, 'd': 'Телепорт с разрядом на месте · Актив · макс 4 · КД 18с', 'effect': 'blink', 'value': 280, 'cd': 18}, {'n': 'Катаклизм Вероятности', 't': 'Ultimate', 'max': 5, 'd': 'Массовый урон + телепорт · Ульта · макс 5 · КД 38с', 'effect': 'chain_lightning', 'value': 135, 'cd': 38} ] },
    2081: { 'name': 'Некро-Сектант', 'abilities': [ {'n': 'Сердце Тьмы', 't': 'Passive', 'max': 5, 'd': 'Хил при убийстве · Пассивно · макс 5', 'effect': 'lifesteal_passive', 'value': 24}, {'n': 'Вызов Скелета', 't': 'Active', 'max': 4, 'd': 'Призывает воина на assistance · Актив · макс 4 · КД 20с', 'effect': 'summon_ward', 'value': 140, 'cd': 20}, {'n': 'Заколдованный Крик', 't': 'Ultimate', 'max': 5, 'd': 'Оглушает и наносит урон по дуге · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 32, 'cd': 36} ] },
    2082: { 'name': 'Шторм-Рыцарь', 'abilities': [ {'n': 'Грозовой Щит', 't': 'Passive', 'max': 5, 'd': 'Энергия при ударе в щит · Пассивно · макс 5', 'effect': 'mana_shield', 'value': 30}, {'n': 'Штурмовая Волна', 't': 'Active', 'max': 4, 'd': 'Скачок с ударной волной · Актив · макс 4 · КД 16с', 'effect': 'leap', 'value': 330, 'cd': 16}, {'n': 'Цепной Удар', 't': 'Ultimate', 'max': 5, 'd': 'Цепная молния по 4 целям · Ульта · макс 5 · КД 36с', 'effect': 'chain_lightning', 'value': 145, 'cd': 36} ] },
    2083: { 'name': 'Скверный Бродяга', 'abilities': [ {'n': 'Засада', 't': 'Passive', 'max': 5, 'd': 'Шанс критического удара из-под Cover · Пассивно · макс 5', 'effect': 'crit_chance', 'value': 30}, {'n': 'Цирковая Бомба', 't': 'Active', 'max': 4, 'd': 'Светошумовая гранатаAoE · Актив · макс 4 · КД 18с', 'effect': 'nova_knockback', 'value': 30, 'cd': 18}, {'n': 'Фокус Смерти', 't': 'Ultimate', 'max': 5, 'd': 'Усиление урона + невидимость · Ульта · макс 5 · КД 36с', 'effect': 'invisibility', 'value': 35, 'cd': 36} ] },
    2084: { 'name': 'Теневой Резак', 'abilities': [ {'n': 'Заточка', 't': 'Passive', 'max': 5, 'd': 'Шанс пробить броню при ударе · Пассивно · макс 5', 'effect': 'armor_break', 'value': 24}, {'n': 'Тень Ножа', 't': 'Active', 'max': 4, 'd': 'Телепорт + мгновенный удар сзади · Актив · макс 4 · КД 16с', 'effect': 'blink', 'value': 280, 'cd': 16}, {'n': 'Карусель Клинков', 't': 'Ultimate', 'max': 5, 'd': 'Вращение вокруг сAoE уроном · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 32, 'cd': 36} ] },
    2085: { 'name': 'Паладин Тьмы', 'abilities': [ {'n': 'Печать Погибели', 't': 'Passive', 'max': 5, 'd': 'Снижает защиту врагам с низкимHP · Пассивно · макс 5', 'effect': 'Execute_low_hp', 'value': 30}, {'n': 'Святой Грааль', 't': 'Active', 'max': 4, 'd': 'Хил+щит на всю команду · Актив · макс 4 · КД 20с', 'effect': 'summon_ward', 'value': 160, 'cd': 20}, {'n': 'Кара Света', 't': 'Ultimate', 'max': 5, 'd': 'Оглушает и наносит урон по зоне · Ульта · макс 5 · КД 36с', 'effect': 'stun_aoe', 'value': 34, 'cd': 36} ] },
    2086: { 'name': 'Ледяной Авангард', 'abilities': [ {'n': 'Сосулька', 't': 'Passive', 'max': 5, 'd': 'Замедляет атакующих врагов · Пассивно · макс 5', 'effect': 'slow', 'value': 38}, {'n': 'Скала Льда', 't': 'Active', 'max': 4, 'd': 'Создаёт ледяную преграду · Актив · макс 4 · КД 18с', 'effect': 'summon_ward', 'value': 150, 'cd': 18}, {'n': 'Снежная Буря', 't': 'Ultimate', 'max': 5, 'd': 'ПостоянноеAoE замедление+урон · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 32, 'cd': 36} ] },
    2087: { 'name': 'Кровавый Авангард', 'abilities': [ {'n': 'Кровавая Ярость', 't': 'Passive', 'max': 5, 'd': 'Увеличивает урон при низком HP · Пассивно · макс 5', 'effect': 'Execute_low_hp', 'value': 34}, {'n': 'Вихрь Крови', 't': 'Active', 'max': 4, 'd': 'Круговой удар с отдачей урона · Актив · макс 4 · КД 18с', 'effect': 'nova_knockback', 'value': 32, 'cd': 18}, {'n': 'Кровавая Магия', 't': 'Ultimate', 'max': 5, 'd': 'Массовый вампиризм на время · Ульта · макс 5 · КД 36с', 'effect': 'lifesteal_passive', 'value': 28, 'cd': 36} ] },
    2088: { 'name': 'Астральный Шепот', 'abilities': [ {'n': 'Звёздный Шёпот', 't': 'Passive', 'max': 5, 'd': 'Усиливает способности при невидимости · Пассивно · макс 5', 'effect': 'invisibility', 'value': 36}, {'n': 'Метание Звёзд', 't': 'Active', 'max': 4, 'd': 'Луч по прямой с уроном · Актив · макс 4 · КД 18с', 'effect': 'blink', 'value': 300, 'cd': 18}, {'n': 'Неминуемая Судьба', 't': 'Ultimate', 'max': 5, 'd': 'Снижает уклонение врагов · Ульта · макс 5 · КД 36с', 'effect': 'slow', 'value': 40, 'cd': 36} ] },
    2089: { 'name': 'Зов Вулкана', 'abilities': [ {'n': 'Огненная Кожа', 't': 'Passive', 'max': 5, 'd': 'Поджигает атакующих врагов · Пассивно · макс 5', 'effect': 'damage_reflect', 'value': 30}, {'n': 'Лавовый Поток', 't': 'Active', 'max': 4, 'd': 'Скачок с извержением лавыAoE · Актив · макс 4 · КД 18с', 'effect': 'aoe_explosion', 'value': 30, 'cd': 18}, {'n': 'Кольцо Огня', 't': 'Ultimate', 'max': 5, 'd': 'Кольцевой огонь: замедляет+урон · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 32, 'cd': 36} ] },
    2090: { 'name': 'Клинок Энтропии', 'abilities': [ {'n': 'Клинок Разлома', 't': 'Passive', 'max': 5, 'd': 'Вероятность сломать броню врага · Пассивно · макс 5', 'effect': 'armor_break', 'value': 28}, {'n': 'Рваная Тень', 't': 'Active', 'max': 4, 'd': 'Рывок сквозь врагов с разрезом · Актив · макс 4 · КД 16с', 'effect': 'blink', 'value': 290, 'cd': 16}, {'n': 'Абсолютный Разлом', 't': 'Ultimate', 'max': 5, 'd': 'РазрезаетAoE с уроном+отбрасыванием · Ульта · макс 5 · КД 36с', 'effect': 'frost_nova', 'value': 34, 'cd': 36} ] },
    2091: { 'name': 'Солнечный Лик', 'abilities': [ {'n': 'Солнечный Щит', 't': 'Passive', 'max': 5, 'd': 'Восстанавливает HP команде · Пассивно · макс 5', 'effect': 'conditionalbuff', 'value': 22}, {'n': 'Вспышка Света', 't': 'Active', 'max': 4, 'd': 'Ослепляет враговAoE · Актив · макс 4 · КД 18с', 'effect': 'stun_aoe', 'value': 30, 'cd': 18}, {'n': 'Солнечный Зов', 't': 'Ultimate', 'max': 5, 'd': 'Массовый урон и хил союзников · Ульта · макс 5 · КД 36с', 'effect': 'summon_ward', 'value': 180, 'cd': 36} ] },
    2092: { 'name': 'Гнев Змея', 'abilities': [ {'n': 'Змеиный Яд', 't': 'Passive', 'max': 5, 'd': 'Накопление урона ядом · Пассивно · макс 5', 'effect': 'slow', 'value': 36}, {'n': 'Змеиный Укус', 't': 'Active', 'max': 4, 'd': 'Быстрый ядовитый удар с замедлением · Актив · макс 4 · КД 16с', 'effect': 'armor_break', 'value': 30, 'cd': 16}, {'n': 'Змеиный Град', 't': 'Ultimate', 'max': 5, 'd': 'Дождь шипов с отравлениемAoE · Ульта · макс 5 · КД 36с', 'effect': 'aoe_explosion', 'value': 32, 'cd': 36} ] },
    2093: { 'name': 'Орёл Небесный', 'abilities': [ {'n': 'Орлиный Глаз', 't': 'Passive', 'max': 5, 'd': 'Ускоряет атаки при падении · Пассивно · макс 5', 'effect': 'cooldown_reduction', 'value': 12}, {'n': 'Небесный Пикировщик', 't': 'Active', 'max': 4, 'd': 'Рывок сверху с ударомAoE · Актив · макс 4 · КД 18с', 'effect': 'leap', 'value': 330, 'cd': 18}, {'n': 'Крик Орла', 't': 'Ultimate', 'max': 5, 'd': 'Оглушает и усиливает союзников · Ульта · макс 5 · КД 36с', 'effect': 'berserk', 'value': 28, 'cd': 36} ] },
}

assert set(updates) <= {r['id'] for r in obj}
for rid, info in updates.items():
    idx = idx_by_id[rid]
    obj[idx]['name'] = info['name']
    obj[idx]['abilities'] = info['abilities']

p.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding='utf-8')
print('D4 updated', len(updates))
